In [22]:
import pandas as pd

/content

In [0]:
data = pd.read_excel('Certificate Data.xlsx',sheet_name='MonthlyInvestment')
data['IssueDate'] = pd.to_datetime(data['IssueDate'])
data_1 = data.groupby(['IssueDate','Consolidate Name']).sum()
data_2 = data.groupby(['IssueDate','MainCurrency']).sum()

In [0]:
data_2.to_csv(r'\C:\Users\Shurong\Downloads\currency1.csv')

In [41]:
# df = pd.read_excel('Data File v7.xlsx',sheet_name='Position Data')
df['NAV Date'] = pd.to_datetime(df['NAV Date'],format='%m/%d/%Y')
df

        Platfrom   ...  Unnamed: 30
0      ZOBEL SCA   ...      Example
1      ZOBEL SCA   ...          NaN
2      ZOBEL SCA   ...  -6.2655e+06
3      ZOBEL SCA   ...          NaN
4      ZOBEL SCA   ... -6.73502e+06
...           ...  ...          ...
12036  ZOBEL SCA   ...          NaN
12037  ZOBEL SCA   ...          NaN
12038  ZOBEL SCA   ...          NaN
12039         NaN  ...          NaN
12040         NaN  ...          NaN

[12041 rows x 31 columns]

In [0]:
df.loc[df['Currency'] == 'LU'] = 'EUR'
df = df.loc[~ (df['Categories'] == 'Cerificate')]

In [0]:
df_2 = df.groupby(['NAV Date','Currency']).sum()
df_2.to_csv('Currencyposition.csv')